### ISSUE TITLE
wrong permissions for linux executables

### ISSUE THREAD

**Issue by RickKimball** [stm32duino/Arduino_Tools#1]
They aren't executable.

stllink_upload 
stlink/st*

chmod +x ... all exes

**Comment by rogerclarkmelbourne** [comment]
Thanks.

This happened because I copied the folders on Windows and the permissions were not retained. 

I will recopy the files using a linux machine, and hopefully pull across the correct permissions

**Comment by rogerclarkmelbourne** [comment]
Hopefully this is fixed in https://github.com/stm32duino/Arduino_Tools/commit/de95abde3ff087840abd15785114cd14c22ebf50
