### ISSUE TITLE
stlink_upload for linux64 out of sync with linux

### ISSUE THREAD

**Issue by RickKimball** [stm32duino/Arduino_Tools#2]
The 32 bit stlink_upload script should be copied to the 64 bit version to bring it up to date.

**Comment by rogerclarkmelbourne** [comment]
Thanks. I just copied the folders from the libmaple version, so it must be missing repo as well

**Comment by rogerclarkmelbourne** [comment]
Hopefully this is fixed in https://github.com/stm32duino/Arduino_Tools/commit/de95abde3ff087840abd15785114cd14c22ebf50
