### ISSUE TITLE
infrared

### ISSUE THREAD

**Issue by ChangChienChung** [stm32duino/Arduino_Tools#38]

**Comment by fpistm** [comment]
Hi @ChangChienChung 
what is your issue ?

**Comment by ChangChienChung** [comment]
Hi, Frederic,

I was trying to find any infra red remote library for the blue pill. I
input the keywords into a search field, and then a message popped up saying
something like starting a thread. All I wanted was to find any existing
library for the infra red remote control. I have tried the IRremote library
for arduino boards. Now I have a need to use ir remote control using blue
pill. Is there a such library now?

Regards,

Frederic Pillon <notifications@github.com>於 2019年7月25日 週四，下午3:07寫道：

**Comment by fpistm** [comment]
I do not know if any IR library was updated to support https://github.com/stm32duino/Arduino_Core_STM32
