### ISSUE TITLE
platform.txt in both F1 and L4 cores looks for the mac os x tools in dir 'macosx' 

### ISSUE THREAD

**Issue by ProjectsByJRP** [stm32duino/Arduino_Tools#4]
rename directory from macos to macosx fixes it

**Comment by rogerclarkmelbourne** [comment]
@ProjectsByJRP

This is unrelated, but I'm having some other issues on OSX ElCapitan.
The old bootloader does not seem to be recognised by ElCapitan.
The new bootloader is recognised but does not seem to get reset correctly after upload (by dfu-util)
There have been some changes to the bootloader to speed up the process between the upload finishing and the sketch running, which may be causing problems on the Mac, but I suspect that what I'm seeing is all to do with ElCapitan :-(

**Comment by ProjectsByJRP** [comment]
I will help you any way I can but
I use Sierra [which probably has whatever bug/feature is causing your error]
I have not changed the boot loader as I’m using the HAL cores
let me know what you would like me to do
-john

**Comment by rogerclarkmelbourne** [comment]
Hi

**Comment by fpistm** [comment]
Close this one as no activities and link to old core.
Could be reopened when BP will be merged in the new core and if issue will be reproduced .
