### ISSUE TITLE
dfu-util Linux 32 bit

### ISSUE THREAD

**Issue by GigiG62** [stm32duino/Arduino_Tools#40]
I'm trying on Linux with a simple example sketch but got an exec format error:
...
/home/gigi/Arduino/hardware/Arduino_STM32/tools/linux/maple_upload: line 40: /home/gigi/Arduino/hardware/Arduino_STM32/tools/linux/dfu-util/dfu-util: cannot execute binary file: Exec format error
Waiting for /dev/ttyACM0 serial...Done

File dfu-util in my folder /home/gigi/Arduino/hardware/Arduino_STM32/tools/linux/dfu-util:
./dfu-util: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib, for GNU/Linux 2.6.32, BuildID[sha1]=c58354ce3ca661a39bc97aacb5beffa73cf5dfb3, with debug_info, not stripped

Editing the maple_upload by commenting out line 39:
DFU_UTIL=/usr/bin/dfu-util
#DFU_UTIL=${DIR}/dfu-util/dfu-util
in order to use system wide dfu-util, give me the error:
...
dfu-util 0.9
Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/
Waiting for /dev/ttyACM0 serial...Done
dfu-util: Invalid DFU suffix signature
dfu-util: A valid DFU suffix will be required in a future dfu-util release!!!
dfu-util: No DFU capable USB device available

Linux Ubuntu 18.04 32 bit on old Acer TravelMate2420, Arduino IDE 1.8.10 with STM32duino bootloader

**Comment by fpistm** [comment]
Hi @GigiG62 
this repo is for this core: https://github.com/stm32duino/Arduino_Core_STM32
not this one: https://github.com/rogerclarkmelbourne/Arduino_STM32/
Tools related to the core you used are part of the core:
https://github.com/rogerclarkmelbourne/Arduino_STM32/tree/master/tools
