### ISSUE TITLE
Flashing with Arduino MCU

### ISSUE THREAD

**Issue by Voha888** [stm32duino/Arduino_Tools#66]
I think this is quite possible? Create such a sketch for arduino-compatible microcontrollers, with which you can flash any STM32 via UART? Or maybe there is a ready-made one?

**Comment by fpistm** [comment]
Hi @Voha888 
this is probably possible but I have no input for this.
This is mainly a question and not an issue so this is better to discuss it on the forum as you made:
https://www.stm32duino.com/viewtopic.php?p=3792#p3792
