### ISSUE TITLE
build_opt.h

### ISSUE THREAD

**Issue by koendv** [stm32duino/Arduino_Tools#76]
A project compiles cleanly under arduino-1.8.13. Under arduino ide 2.0.0 compilation fails. (log attached).
The project compiles cleanly under ide 2.0.0 if the file 'build_opt.h' is deleted:

```
$ more build_opt.h 
-DUSB_PRODUCT_STRING=\"vacuum\ pump\ controller\"
```
opinion?

[output.txt](https://github.com/stm32duino/Arduino_Tools/files/6583563/output.txt)

**Comment by fpistm** [comment]
Hi @koendv 
This is not the correct repo to talk about build_opt.h it relies to the core not the tools.
This issue already ben raised:
https://github.com/stm32duino/Arduino_Core_STM32/issues/1387

Then I've open an issue to Arduino IDE:
https://github.com/arduino/arduino-ide/issues/363

But currently no feedback.
